import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import dynamic from "next/dynamic";

const RosterMaker = dynamic(() => import("../ui/RosterMaker"), { ssr: false });

// import RosterMaker from "~/ui/RosterMaker";

import { api } from "~/utils/api";
import { Button } from "~/ui/primitive/Button";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const darkMode = {
    ["data-theme"]: "dark",
  };

  return (
    <>
      <Head>
        <title>TFR Roster Builder</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col space-y-8 bg-gradient-to-b from-[#2e026d] to-[#15162c] px-8 py-12 text-white md:px-16 xl:px-24">
        <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
          The TFR <span className="text-[hsl(280,100%,70%)]">Portal</span>
        </h1>
        <p className="ml-2 text-3xl">Welcome, draskal jr.</p>
        <div className="grid grid-cols-2 gap-8">
          <div
            {...darkMode}
            className="relative mt-4 min-h-[250px] min-w-[33%] rounded-md border border-neutral-300 p-4 text-neutral-800 dark:bg-neutral-800"
            // className="relative mt-4 min-h-[250px] min-w-[33%] rounded-md border border-neutral-300 p-4 pb-12 text-neutral-800 dark:bg-neutral-800"
          >
            <div className="grid h-full w-full place-content-center">
              <Button>Manage Builds</Button>
            </div>
            {/* <div className="grid gap-2">
              <div className="grid grid-flow-col rounded border-b border-b-neutral-300 bg-neutral-200 p-2 pl-6">
                <h2 className="font-semibold">Role</h2>
                <h2 className="font-semibold">Weapon 1</h2>
                <h2 className="font-semibold">Weapon 2</h2>
                <h2 className="font-semibold">Heartrune</h2>
                <h2 className="font-semibold">Wars Played</h2>
              </div>
              <div className="grid grid-flow-col rounded p-2 pl-6 odd:bg-neutral-100 even:bg-purple-50">
                <p className="">Role</p>
                <p className="">Weapon 1</p>
                <p className="">Weapon 2</p>
                <p className="">Heartrune</p>
                <p className="">Wars Played</p>
              </div>
              <div className="grid grid-flow-col rounded p-2 pl-6 odd:bg-neutral-100">
                <p className="">Role</p>
                <p className="">Weapon 1</p>
                <p className="">Weapon 2</p>
                <p className="">Heartrune</p>
                <p className="">Wars Played</p>
              </div>
            </div>
            <div className="absolute bottom-2 flex w-full">
              <Button>Manage Builds</Button>
            </div> */}
          </div>
          <div className="mt-4 grid min-h-[250px] min-w-[33%] place-content-center rounded-md border border-neutral-300 p-4">
            <Button>
              War Records, Announcements, Knowledge base, Group finder
            </Button>
          </div>

          <div
            {...darkMode}
            className="col-span-2 min-h-[250px] rounded-md border border-neutral-300 p-4"
          >
            <Link className="grid place-content-center" href={"/roster"}>
              <Button>Manage Roster</Button>
            </Link>
          </div>
        </div>
        <div className="flex flex-col items-center justify-start gap-12 px-4 py-16 ">
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div>
        <div className="w-full ">
          <RosterMaker />
        </div>
      </main>
    </>
  );
};

export default Home;
